export type MiembroDashboardSection =
    | "inicio"
    | "citas"
    | "beneficios"
    | "reportes"
    | "ajustes"
    | "admin_citas"
    | "admin_beneficios"
    | "admin_documentos"
    | "admin_usuarios"
    | "admin_empresas"
    | "empresa_citas"
    | "empresa_ajustes"
    | "empresa_usuarios"
    | "mi_familia";
